import { expandedTeraboxNames, teraboxCabellosalirrosasNames, teraboxCabellosalirrosasSecondNames, teraboxJxaviercabellosNames, teraboxSlug, TERABOX_CABELLOSALIRROSAS_ACCOUNT_EMAIL, TERABOX_JXAVIERCABELLOS_ACCOUNT_EMAIL } from "./teraboxCatalog";

export type LearningRoute = {
  id: string;
  label: string;
  shortLabel: string;
  description: string;
  accent: string;
};

export type CourseSource = "google_drive" | "terabox";

export const TERABOX_SOURCE_ACCOUNT_EMAIL = "juanxaviercasa@gmail.com";

export type CourseMeta = {
  id: string;
  source?: CourseSource;
  sourceAccountEmail?: string;
  routeId: string;
  order: number;
  title: string;
  description: string;
  whatYouLearn: string;
  startHere: string;
  outcome: string;
  coverImageUrl?: string;
  coverImageNote?: string;
};

export const learningRoutes: LearningRoute[] = [
  { id: "business", label: "Negocio y Agencia", shortLabel: "Negocio", description: "Oferta, operación, adquisición y sistemas para construir una agencia sólida.", accent: "amber" },
  { id: "sales", label: "Ventas y Negociación", shortLabel: "Ventas", description: "Proceso comercial, conversación, cierre y prospección multicanal.", accent: "coral" },
  { id: "content", label: "Contenido y Redes", shortLabel: "Contenido", description: "Estrategia, producción, distribución y monetización de contenido.", accent: "violet" },
  { id: "ecommerce", label: "Ecommerce", shortLabel: "Ecommerce", description: "Diseño, captación, operación y escalado de una tienda digital.", accent: "mint" },
  { id: "ai", label: "IA y Creación", shortLabel: "IA", description: "Investigación, creación y lanzamiento de productos educativos con IA.", accent: "sky" },
  { id: "finance", label: "Finanzas y Desarrollo Personal", shortLabel: "Finanzas", description: "Biblioteca separada de educación financiera y mentalidad.", accent: "rose" },
  { id: "fitness", label: "Salud y Rendimiento", shortLabel: "Salud", description: "Programas de entrenamiento, nutrición y hábitos físicos organizados por objetivo.", accent: "lime" },
];

export const courseMeta: CourseMeta[] = [
  { id: "1hw3D8i-33NPwKi8C5MVcCq8XxjBaBl-B", routeId: "business", order: 1, title: "AMG", description: "Ruta de agencia en tres fases: operación, clientes e ingresos.", whatYouLearn: "Estructurar una agencia, captar clientes y convertir el servicio en ingresos sostenibles.", startHere: "Fase 1 — Tu Agencia", outcome: "Un mapa operativo para tu agencia y sus prioridades comerciales." },
  { id: "1gP3-D_4oelnV0w5xQHHWg5KPIJCq5RPw", routeId: "business", order: 2, title: "SMMA", description: "Sistema práctico para desarrollar y operar una agencia de social media.", whatYouLearn: "Fundamentos, operación, subcontratación, prospección y cierre.", startHere: "1. FUNDAMENTOS", outcome: "Una base operativa para ofrecer y gestionar servicios de marketing." },
  { id: "1Z1a7Yn_3hGT5cEOCbVmGzhjtjz3aiReH", routeId: "business", order: 3, title: "Plan de acción para agencias web", description: "Blueprint para crear una agencia web de adquisición a entrega.", whatYouLearn: "Fundación, adquisición, fulfillment y llamadas de venta.", startHere: "00 — The Web Agency Blueprint", outcome: "Un plan de acción para lanzar o ordenar una agencia web." },
  { id: "1QRrjTxcggVXl5iGJ2lpSCmBUU-PmVw3Y", routeId: "business", order: 4, title: "Business Accelerator", description: "Biblioteca de crecimiento empresarial y sistemas de escalado.", whatYouLearn: "Crecimiento rápido, estrategia y herramientas de negocio.", startHere: "01 — Welcome to Business Accelerator", outcome: "Un sistema de prioridades para acelerar el crecimiento del negocio." },
  { id: "1YpBQR8Ol_Mx5H5FQwbsyYrWnsc7t1Baf", routeId: "business", order: 5, title: "Biblioteca de negocios", description: "Colección de subcursos de negocio, ecommerce, copywriting y freelancing.", whatYouLearn: "Elegir una especialización y profundizar con itinerarios complementarios.", startHere: "Business Mastery o el subcurso alineado a tu objetivo", outcome: "Una ruta complementaria elegida con intención, sin mezclar cursos al azar." },
  { id: "1HmLxqpyBLRXjK36YuTme1ZQgJ1GRlloe", routeId: "sales", order: 1, title: "Real Sales System", description: "Fundamentos de actividad comercial y descubrimiento del dolor del cliente.", whatYouLearn: "Diseñar un proceso comercial y conducir conversaciones de diagnóstico.", startHere: "1 — Activity & Process", outcome: "Un proceso base de prospección y conversación de ventas." },
  { id: "1V5JbOWfJGBzanXcHgEFZbISxK39rSX0z", routeId: "sales", order: 2, title: "Sales Negotiation", description: "Ruta estructurada de negociación, objeciones y cierre.", whatYouLearn: "Cerrar ventas con claridad, gestionar objeciones y reforzar la propuesta.", startHere: "01 — Negotiating And Closing Master Class", outcome: "Un marco de conversación y negociación aplicable a ofertas propias." },
  { id: "1u0vWzbFsGK3N1_G4oklznFyLBaS73DcR", routeId: "sales", order: 3, title: "Jordan Belfort 4 in 1", description: "Colección de psicología de ventas, guiones y marketing directo.", whatYouLearn: "Persuasión responsable, estructuración de guiones y mensaje comercial.", startHere: "Inner Game of Wealth", outcome: "Un guion de ventas y una estructura de comunicación más consistente." },
  { id: "1hDv1GqR56zuf45BDbGIlyTwvqZCKN78f", routeId: "sales", order: 4, title: "Cardone U", description: "Biblioteca de ventas con práctica de prospección, respuesta y cierre.", whatYouLearn: "Fundamentos, buyer understanding, llamadas entrantes y estrategias de cierre.", startHere: "Selling Basics", outcome: "Una biblioteca de práctica para reforzar cada etapa del proceso comercial." },
  { id: "17Eryb74Ci713Vdkp-wtkGvF7lLiwvzUA", routeId: "sales", order: 5, title: "Cold Email Cash Flow", description: "Sistema de prospección por correo con investigación, oferta y seguimiento.", whatYouLearn: "Crear listas, mensajes, asuntos y secuencias de seguimiento.", startHere: "Módulos de investigación, objetivo y oferta", outcome: "Una campaña inicial de cold email documentada y medible." },
  { id: "1ztNbicfwwYN9GqsR34hbG4GeSaDB2t7G", routeId: "content", order: 1, title: "Víctor Heras · ViralCopy", description: "Base de estrategia de contenido, ganchos y narrativas para redes.", whatYouLearn: "Entender algoritmo, ideas, viralidad, hooks, historias y CTA.", startHere: "1 — Introducción", outcome: "Una pieza de contenido con gancho, historia y llamada a la acción." },
  { id: "1oRjIfdjSXDOcjX8dhvgDjmJZY6YuOB8D", routeId: "content", order: 2, title: "YouTube Monetization Blueprint", description: "Itinerario de nicho, canal, empaquetado, vídeo y monetización.", whatYouLearn: "Definir un nicho, configurar un canal y publicar vídeos con intención.", startHere: "01 — Welcome to your new life", outcome: "Un plan editorial inicial para un canal de YouTube." },
  { id: "1efyGwfNu4R4yPqPZQhYdICexl710WFVY", routeId: "content", order: 3, title: "Video Success", description: "Curso de presencia en cámara, estrategia de vídeo y marca personal.", whatYouLearn: "Vencer bloqueos, producir vídeo y escalar una marca mediante contenido.", startHere: "01 — Start Here", outcome: "Un sistema de vídeo que conecta contenido, audiencia y negocio." },
  { id: "1q0pIvywpGjpkfCRsK5rgt-i8u1JR1fU5", routeId: "content", order: 4, title: "IG AI-CCELERATOR", description: "Sistema de Instagram desde audiencia hasta optimización de rendimiento.", whatYouLearn: "Investigar avatar, posicionar perfil, crear contenido y medir resultados.", startHere: "01 — Start here", outcome: "Un perfil y una estrategia de contenido para Instagram." },
  { id: "1YJVvTnnDszvDktdngSO3Nc5pJiIjj9PI", routeId: "content", order: 5, title: "AI Pinterest Masterclass", description: "Aplicación de Pinterest con una base estratégica y un paso a paso.", whatYouLearn: "Preparar la estrategia y ejecutar un flujo de Pinterest asistido por IA.", startHere: "1 — Groundwork", outcome: "Un flujo inicial de distribución de contenido en Pinterest." },
  { id: "1te8gdotGcO3aGYdbzBQDntsKLBynANL7", routeId: "ecommerce", order: 1, title: "Ecommerce · Vilma Núñez", description: "Programa integral para construir, comunicar, operar y escalar una tienda online.", whatYouLearn: "Audiencia, producto, copy, métricas, campañas, logística y escalado.", startHere: "1. Bases fundamentales", outcome: "Un plan operativo de ecommerce con etapas claras de ejecución." },
  { id: "1KI2_liZ6FdmyGlOqkSfpP5SdllATiRp_", routeId: "ai", order: 1, title: "AI Course Creator", description: "Ruta para investigar, estructurar, crear y lanzar un curso con IA.", whatYouLearn: "Prompts, audiencia, contenido, plataforma y lanzamiento.", startHere: "1 — How to get the prompts", outcome: "La estructura y el plan de lanzamiento de un producto educativo." },
  { id: "18cex53JQW1RjNG4SNzLb766Uof6DdjLi", routeId: "finance", order: 1, title: "Tarjetas de crédito con inteligencia", description: "Curso independiente sobre conceptos básicos de tarjetas y uso responsable.", whatYouLearn: "Conceptos de franquicias, cupo, interés, corte y comportamiento de consumo.", startHere: "VIDEO 1 — Introducción al mundo de las tarjetas", outcome: "Un glosario y una comprensión ordenada de los conceptos del curso." },
  { id: "1KjkN9DUWnJzOdgrlwJEu2x4oei9szFHS", routeId: "finance", order: 2, title: "Millionaire", description: "Biblioteca de mentalidad y hábitos de crecimiento personal.", whatYouLearn: "Reflexionar sobre creencias, objetivos y mentalidad de largo plazo.", startHere: "Unlock the Millionaire Within · Part 1", outcome: "Un plan personal de hábitos y objetivos, separado de decisiones financieras." },
  { id: "1IkRomy3M6h9RfDKSln9NjW-Q4x7FZJ2p", routeId: "fitness", order: 1, title: "Kinobody · 30 Day Working Out", description: "Programa visual de entrenamiento estructurado para construir una práctica de treinta días.", whatYouLearn: "Ordenar una rutina diaria, seguir una progresión visual y sostener la consistencia de entrenamiento.", startHere: "Programa visual de entrenamiento de 30 días", outcome: "Un calendario personal de entrenamiento para completar el programa con seguimiento." },
  { id: "1dxvel2jEarUb7ijNesZULpHQmbpM0bDa", routeId: "fitness", order: 2, title: "Kinobody · Aggressive Fat Loss 2.0", description: "Biblioteca de guía, entrenamiento, nutrición, calculadora y recursos de acompañamiento.", whatYouLearn: "Comprender el material del programa, organizar un plan de comidas y consultar sus recursos de entrenamiento.", startHere: "01 · Guía principal", outcome: "Una secuencia personal de revisión de guía, entrenamiento, comidas y recursos complementarios.", coverImageUrl: "/manus-storage/kinobody-drinking-guide-concept_169b6d33.png", coverImageNote: "Portada conceptual generada por la plataforma; no sustituye ni representa la portada oficial del documento original." },
  { id: "1C0jkpBEP67eGfw9w2QvylDifOOxc2hnZ", routeId: "fitness", order: 3, title: "Kinobody · Greek God Muscle Building", description: "Programa de construcción muscular con guía, preguntas frecuentes y una división de tres días.", whatYouLearn: "Navegar la guía del programa, resolver preguntas frecuentes y ubicar la división complementaria.", startHere: "Guía del programa de construcción muscular", outcome: "Una estructura de estudio del programa y sus materiales de apoyo." },
  { id: "1hGCKVpEUdS8H6FefY4Th-_GH1XQT0Evt", routeId: "fitness", order: 4, title: "Kinobody · KINOCHEF", description: "Colección culinaria con recetario principal y dos bibliotecas adicionales de recetas.", whatYouLearn: "Ubicar recetas principales y complementar la planificación de comidas con recursos culinarios.", startHere: "KinoChef · Recetario completo", outcome: "Una selección de recetas para acompañar la organización personal de comidas." },
  { id: "16CSfE6f_NUo_AWLobnCwCxbWW4ZWvJwr", routeId: "fitness", order: 5, title: "Kinobody · SuperHero Bulking", description: "Manual completo del programa de aumento de masa.", whatYouLearn: "Recorrer de forma ordenada el manual y registrar los puntos de acción relevantes para tu práctica.", startHere: "Manual completo de SuperHero Bulking", outcome: "Una guía de estudio organizada del material de aumento de masa." },
  { id: "14qYxKwwDHMtxXwzExn_ZDQ3v55QAH97k", routeId: "fitness", order: 6, title: "Kinobody · Warrior Shredding", description: "Programa principal con FAQ y capítulo de apoyo.", whatYouLearn: "Explorar el programa, consultar preguntas frecuentes y revisar el material complementario.", startHere: "Programa Warrior Shredding", outcome: "Una ruta de estudio clara para revisar el programa y sus apoyos." },
  { id: "1qyEz3Tq3snDDpW2Co3SmvL3cOfO-sZ-C", source: "google_drive", routeId: "sales", order: 6, title: "Chat GPT Marketing para Ventas Exitosas", description: "Curso práctico para aplicar ChatGPT a la estrategia y ejecución comercial.", whatYouLearn: "Investigar oportunidades, crear mensajes y acelerar tareas de marketing con IA.", startHere: "Chat GPT Marketing para Ventas Exitosas 1", outcome: "Una primera secuencia de mensajes y tareas de marketing asistidas por IA." },
  { id: "19VBkN0GelCU2Fr_aOg74trWGSKiQB2nM", source: "google_drive", routeId: "ai", order: 2, title: "IA para Investigar tu Mercado", description: "Método para investigar y comprender un mercado usando herramientas de inteligencia artificial.", whatYouLearn: "Formular preguntas, analizar información y convertir investigación en decisiones de mercado.", startHere: "Cómo Utilizar la IA para Investigar y Entender tu Mercado 1", outcome: "Un esquema de investigación de mercado asistido por IA." },
  { id: "1fALqYvE8SuygpVi88NfJtCUg42x-4Z1H", source: "google_drive", routeId: "content", order: 6, title: "Copywriting: Mensajes que Venden", description: "Curso de escritura persuasiva para comunicar ofertas con mayor claridad.", whatYouLearn: "Construir mensajes, titulares y argumentos orientados a conversión responsable.", startHere: "Copywriting Mensajes que Venden 1", outcome: "Una estructura de mensaje comercial lista para revisar y adaptar." },
  { id: "1dQTdsKNyGrnPlA-KDTRZDS62ZhPzV48o", source: "google_drive", routeId: "content", order: 7, title: "Creación y Planeación de Contenido para Instagram", description: "Sistema para planificar y producir contenido consistente para Instagram.", whatYouLearn: "Definir temas, planificar publicaciones y conectar contenido con objetivos de audiencia.", startHere: "Creación y Planeación de Contenido para Instagram 1", outcome: "Un calendario inicial de contenido para Instagram." },
  { id: "1On52JnLs86YPjQdgYhaD1hzXszOYFmzo", source: "google_drive", routeId: "business", order: 6, title: "Entendiendo el Marketing Digital", description: "Introducción ordenada a los fundamentos del marketing digital.", whatYouLearn: "Reconocer canales, audiencias y acciones básicas de marketing digital.", startHere: "Entendiendo el Marketing Digital", outcome: "Un mapa inicial de canales y prioridades de marketing digital." },
  { id: "1aAGE6c5xN8FoPgHbqf9FFtcExCB0HBGj", source: "google_drive", routeId: "ai", order: 3, title: "Tu Agencia de Expertos en IA", description: "Ruta para entender y estructurar una agencia de servicios apoyados por inteligencia artificial.", whatYouLearn: "Identificar oportunidades de servicio, organizar entregables y comunicar una propuesta de valor con IA.", startHere: "Tu Agencia de Expertos en Inteligencia Artificial (IA) 1", outcome: "Un esquema inicial de oferta para una agencia de expertos en IA." },
  { id: "terabox-jxcasa-ai-digital-marketing-guide", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 7, title: "AI-Powered Digital Marketing Guide", description: "Biblioteca de marketing digital, publicidad, analítica, SEO, ecommerce y campañas Meta/Google.", whatYouLearn: "Recorrer fundamentos de marketing digital y conectar adquisición, analítica, SEO, ecommerce y publicidad.", startHere: "Digital Marketing Essentials", outcome: "Un mapa de estudio para ordenar fundamentos, canales y campañas." },
  { id: "terabox-jxcasa-ai-automation-agency", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 8, title: "AI Automation Agency", description: "Curso centrado en la creación y operación de una agencia de automatización con IA.", whatYouLearn: "Identificar servicios de automatización y ordenar una propuesta operativa.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un esquema inicial de oferta para una agencia de automatización." },
  { id: "terabox-jxcasa-kcpqhdfcc", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 9, title: "KCPQHDFCC", description: "Certificación Family Coach con diez módulos, incluidos pasos finales y recursos de certificación.", whatYouLearn: "Recorrer la secuencia de Quantum Human Design, condicionamiento, motivaciones y coaching familiar.", startHere: "00 — Quantum Human Design Family Coach Certification", outcome: "Una ruta ordenada de estudio por módulos para completar la formación y revisar sus recursos finales." },
  { id: "terabox-jxcasa-onlyfans-agency", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 10, title: "How to Create a Successful OnlyFans Agency", description: "Curso de operación de agencia con 18 capítulos en vídeo y dos plantillas reales verificadas.", whatYouLearn: "Revisar captación de modelos, contratos, producción, promoción, automatización y gestión de una agencia.", startHere: "01 — Introduction.mp4", outcome: "Un mapa de procesos de agencia basado en los archivos visibles del curso original." },
  { id: "terabox-jxcasa-millionaire-speakers", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "finance", order: 3, title: "Millionaire Speakers Leadership Influence Mastery", description: "Programa de liderazgo, influencia y desarrollo personal.", whatYouLearn: "Ordenar conceptos de liderazgo, comunicación e influencia personal.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un plan de reflexión y práctica de liderazgo." },
  { id: "terabox-jxcasa-how-to-use-ai-to-make-money", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "ai", order: 4, title: "How to Use AI to Make Money", description: "Biblioteca de aplicaciones prácticas de inteligencia artificial para crear oportunidades de negocio.", whatYouLearn: "Explorar usos de IA y convertirlos en ideas de oferta revisables.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un inventario de oportunidades de aplicación de IA." },
  { id: "terabox-jxcasa-chatgpt-make-money-ai-canva", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "ai", order: 5, title: "ChatGPT, AI & Canva 2025", description: "Curso práctico que combina ChatGPT, creación con IA y Canva.", whatYouLearn: "Organizar un flujo de ideación, producción y publicación asistido por IA.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un flujo inicial para producir un recurso digital con IA." },
  { id: "terabox-jxcasa-bob-proctor-thinking-results", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "finance", order: 4, title: "Bob Proctor — Thinking into Results", description: "Programa de mentalidad y objetivos de desarrollo personal.", whatYouLearn: "Reflexionar sobre objetivos, hábitos y consistencia personal.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un plan personal de objetivos y hábitos." },
  { id: "terabox-jxcasa-mindvalley-mystic-brain", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "finance", order: 5, title: "MindValley — Mystic Brain", description: "Programa de desarrollo personal identificado en la biblioteca Terabox.", whatYouLearn: "Revisar sus lecciones y separar conceptos de práctica personal.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Una secuencia de revisión personal basada en el contenido original." },
  { id: "terabox-jxcasa-facebook-monetization", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "content", order: 8, title: "Facebook Monetization", description: "Curso de monetización de Facebook desde fundamentos hasta contenidos avanzados.", whatYouLearn: "Ordenar audiencia, contenido y vías de monetización en Facebook.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un esquema de contenidos y monetización para Facebook." },
  { id: "terabox-jxcasa-saad-automation", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 11, title: "Saad Automation", description: "Biblioteca de automatización para procesos y servicios digitales.", whatYouLearn: "Identificar procesos repetibles y oportunidades de automatización.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un mapa inicial de procesos automatizables." },
  { id: "terabox-jxcasa-fitness-programs", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "fitness", order: 7, title: "Fitness Programs", description: "Carpeta de programas de entrenamiento y rendimiento físico.", whatYouLearn: "Revisar los programas originales y escoger una secuencia de entrenamiento coherente.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Una ruta de entrenamiento pendiente de detallar por programa." },
  { id: "terabox-jxcasa-russell-brunson-secrets", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 12, title: "Russell Brunson — Secrets", description: "Biblioteca de marketing, embudos y crecimiento de ofertas.", whatYouLearn: "Revisar conceptos de oferta, adquisición y sistemas de conversión.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un esquema inicial de embudo y propuesta de valor." },
  { id: "terabox-jxcasa-kamal-cpm", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 13, title: "Kamal CPM Full Course", description: "Curso Terabox pendiente de inspección interna detallada.", whatYouLearn: "Revisar el contenido original y ubicarlo en la ruta pedagógica correcta.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Una clasificación confirmada después de revisar sus módulos." },
  { id: "terabox-jxcasa-brandon-digital-freedom", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 14, title: "Brandon Timothy — Digital Freedom Academy", description: "Programa de negocio digital y libertad financiera identificado en Terabox.", whatYouLearn: "Separar fundamentos, acciones y recursos prácticos del programa.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un itinerario inicial de negocio digital." },
  { id: "terabox-jxcasa-jk-molina-cash-creators", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "business", order: 15, title: "JK Molina — Cash Creators", description: "Bundle de creación de ingresos y productos digitales.", whatYouLearn: "Revisar modelos de oferta y acciones de creación de ingresos.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Una lista priorizada de hipótesis de oferta." },
  { id: "terabox-jxcasa-caitlin-hard-as-you-want", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "fitness", order: 8, title: "Caitlin V — Hard As You Want Course", description: "Programa de entrenamiento identificado en la carpeta Terabox.", whatYouLearn: "Revisar la estructura de entrenamiento y sus materiales originales.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Una secuencia de práctica física pendiente de detallar." },
  { id: "terabox-jxcasa-etsy-academy", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "ecommerce", order: 2, title: "Growing Your Craft — Etsy Academy 2.0", description: "Programa de creación y crecimiento de una tienda en Etsy.", whatYouLearn: "Ordenar producto, presentación, adquisición y operación de una tienda creativa.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un plan inicial para estructurar una tienda en Etsy." },
  { id: "terabox-jxcasa-matt-par-tube-ai", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "content", order: 9, title: "Matt Par — Tube AI System", description: "Sistema de creación y crecimiento de contenido para YouTube con apoyo de IA.", whatYouLearn: "Revisar nicho, producción, empaquetado y distribución de vídeos.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un plan editorial inicial para YouTube." },
  { id: "terabox-jxcasa-david-tian-social-circle", source: "terabox", sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL, routeId: "sales", order: 7, title: "David Tian — Social Circle Mastery", description: "Programa de comunicación y relaciones sociales identificado en Terabox.", whatYouLearn: "Revisar comunicación interpersonal y convertir el contenido en prácticas responsables.", startHere: "Abrir la carpeta del curso en Terabox", outcome: "Un plan de práctica de comunicación interpersonal." },
  ...expandedTeraboxNames.map((title, index) => ({
    id: `terabox-jxcasa-${teraboxSlug(title)}`,
    source: "terabox" as const,
    sourceAccountEmail: TERABOX_SOURCE_ACCOUNT_EMAIL,
    routeId: /ecom|shopify|etsy|print on demand|ecommerce/i.test(title) ? "ecommerce" : /sales|closing|cardone|appointment|prospecting|offer/i.test(title) ? "sales" : /ai|chatgpt|notion|deepfake|supermind/i.test(title) ? "ai" : /social|youtube|viral|content|media/i.test(title) ? "content" : "business",
    order: 20 + index,
    title,
    description: "Curso Terabox incorporado desde el inventario visible; pendiente de inspección interna detallada.",
    whatYouLearn: "Revisar el contenido original y ordenar sus módulos cuando se disponga de la navegación interna.",
    startHere: "Abrir la carpeta del curso en Terabox",
    outcome: "Una ruta pedagógica confirmada después de inspeccionar sus archivos.",
  })),
  ...teraboxCabellosalirrosasNames.map((title, index) => ({
    id: `terabox-cabellosalirrosas-${teraboxSlug(title)}`,
    source: "terabox" as const,
    sourceAccountEmail: TERABOX_CABELLOSALIRROSAS_ACCOUNT_EMAIL,
    routeId: /chatgpt|ai|transcribe|prompt|curso con ia|manychat|codigo/i.test(title) ? "ai" : /marketing|ventas|million|profit|formula|nichos|paraiso|social media/i.test(title) ? "business" : /amigurumis|yoga|merengue|nitrofit/i.test(title) ? "fitness" : /seduccion/i.test(title) ? "sales" : "content",
    order: 30 + index,
    title,
    description: "Curso Terabox incorporado desde el enlace compartido de cabellosalirrosas; la ficha conserva el acceso original y queda pendiente de inspección interna detallada.",
    whatYouLearn: "Recorrer el contenido original y convertir sus archivos en una secuencia práctica de aprendizaje.",
    startHere: "Abrir la carpeta del curso en Terabox",
    outcome: "Una ruta pedagógica organizada después de revisar sus módulos y recursos.",
  })),
  ...teraboxCabellosalirrosasSecondNames.map((title, index) => ({
    id: `terabox-cabellosalirrosas-second-${teraboxSlug(title)}`,
    source: "terabox" as const,
    sourceAccountEmail: TERABOX_CABELLOSALIRROSAS_ACCOUNT_EMAIL,
    routeId: /english|developer|libros|contable|llc|escuela|infoproducto|courses/i.test(title) ? "ai" : /ventas|vsl|youtube|seo|marketing|million|dinero|brandon|alex pereira|victor heras|ian bernal/i.test(title) ? "business" : /duerme|fitness|salud/i.test(title) ? "fitness" : "content",
    order: 60 + index,
    title,
    description: "Curso Terabox del segundo enlace compartido de cabellosalirrosas; incorporado con acceso de origen y pendiente de inspección interna detallada.",
    whatYouLearn: "Recorrer el material original y transformarlo en una secuencia de estudio con objetivos y prácticas concretas.",
    startHere: "Abrir la carpeta del curso en Terabox",
    outcome: "Una ruta de aprendizaje organizada después de validar sus módulos y recursos.",
  })),
  ...teraboxJxaviercabellosNames.map((title, index) => ({
    id: `terabox-jxaviercabellos-${teraboxSlug(title)}`,
    source: "terabox" as const,
    sourceAccountEmail: TERABOX_JXAVIERCABELLOS_ACCOUNT_EMAIL,
    routeId: /viral|content|video|instagram|social|editing|tiktok|voice|seo|topical|youtube/i.test(title) ? "content" : /sales|selling|listing|local riches|ecom|infoproducto|fund your purpose/i.test(title) ? "business" : /karma|energy|productivity|english|libros/i.test(title) ? "ai" : "business",
    order: 90 + index,
    title,
    description: "Curso Terabox del tercer enlace compartido de jxaviercabellos; incorporado con acceso de origen y pendiente de inspección interna detallada.",
    whatYouLearn: "Recorrer el material original y convertirlo en una ruta de estudio práctica, con ejercicios y recursos de apoyo.",
    startHere: "Abrir la carpeta del curso en Terabox",
    outcome: "Una secuencia de aprendizaje organizada después de validar sus módulos y archivos.",
  })),
];

export function getCourseSource(meta: CourseMeta): CourseSource {
  return meta.source ?? "google_drive";
}

export const courseMetaById = Object.fromEntries(courseMeta.map((course) => [course.id, course]));
