import type { DubbingSetup } from "@shared/learning";
import { AudioLines, Captions, CheckCircle2, ChevronRight, KeyRound, Languages, Sparkles } from "lucide-react";

export function DubbingPanel({ setup, isPilotReady }: { setup: DubbingSetup; isPilotReady: boolean }) {
  return <section className="dubbing-placeholder" aria-labelledby="dubbing-placeholder-title">
    <div className="dubbing-head"><div className="dubbing-icon"><AudioLines size={21} /></div><div><span>{isPilotReady ? "PILOTO DISPONIBLE · ESPAÑOL" : "ESTADO ACTUAL · NO ACTIVADO"}</span><h2 id="dubbing-placeholder-title">{isPilotReady ? "El vídeo piloto ya puede escucharse en español." : "Doblaje al español aún no disponible"}</h2><p>{isPilotReady ? "Al abrir el vídeo preparado del módulo uno, la pista española se selecciona por defecto. Puedes volver al audio original desde el selector del reproductor." : "No se ha generado una pista de audio española. Este curso se reproduce hoy con su audio original en inglés."}</p></div></div>
    <div className={`dubbing-audio-status ${isPilotReady ? "dubbing-audio-status--ready" : ""}`}><AudioLines size={17} /><div><b>{isPilotReady ? "Audio español disponible: módulo uno" : "Audio disponible ahora: original · inglés"}</b><span>{isPilotReady ? "El doblaje local y los subtítulos en español están listos para el vídeo piloto. Los demás módulos se mantienen en idioma original hasta ser procesados." : "La voz española y los subtítulos en español aparecerán únicamente después de procesar el vídeo con un proveedor configurado."}</span></div></div>
    <details className="pending-details dubbing-details"><summary>Ver plan técnico de doblaje futuro <span>No activo</span></summary><div className="dubbing-pipeline">{setup.pipeline.map((stage, index) => <div className="dubbing-stage" key={stage.step}><b>{String(index + 1).padStart(2, "0")}</b><span>{stage.step}</span><small>{stage.output}</small>{index < setup.pipeline.length - 1 && <ChevronRight className="dubbing-arrow" size={15} />}</div>)}</div>
      <div className="dubbing-provider-grid">{setup.providers.map((provider) => <article aria-disabled="true" className={`dubbing-provider dubbing-provider--${provider.tier} ${provider.recommended ? "dubbing-provider--recommended" : ""}`} key={provider.id}><div><span>{provider.tier === "free" ? "RUTA GRATUITA" : "OPCIONAL"}</span>{provider.recommended && <em><Sparkles size={11} /> RECOMENDADA</em>}</div><h3>{provider.label}</h3><p>{provider.description}</p></article>)}</div>
      <div className="dubbing-controls"><div className="dubbing-track-preview"><Languages size={16} /><span>Idiomas futuros</span><b>Inglés <ChevronRight size={13} /> Español</b></div><div className="dubbing-track-preview"><Captions size={16} /><span>Resultado futuro</span><b>Original · Español · Subtítulos</b></div></div>
      <div className="dubbing-keys"><div><KeyRound size={16} /><span>Integración por completar</span></div><p>Los secretos se añaden después en el servidor; no se guardan claves ni se envía información al navegador.</p><div>{setup.placeholders.map((field) => <code title={field.purpose} key={field.key}>{field.key}<small>{field.example}</small></code>)}</div><p className="dubbing-rights"><CheckCircle2 size={14} /> La traducción debe revisarse y utilizarse únicamente cuando se tenga derecho a adaptar el contenido.</p></div></details>
  </section>;
}
